// Card Mystery Realm — Full card pool (206 cards)
// Common×120, Rare×50, Epic×25, Legendary×8, Mythic×3

export type Rarity = 'common' | 'rare' | 'epic' | 'legendary' | 'mythic';

export interface CardTemplate {
  id: number;
  name: string;
  rarity: Rarity;
  icon: string;
  series: string;
  story?: string;
}

export const CARD_TEMPLATES: CardTemplate[] = [
  // ── Common — Volcanic Origins (60) ───────────────────────────────────────
  { id:1,  name:'Ember Lizard',      rarity:'common', icon:'🦎', series:'Volcanic Origins' },
  { id:2,  name:'Ash Sprite',        rarity:'common', icon:'🔥', series:'Volcanic Origins' },
  { id:3,  name:'Stone Golem',       rarity:'common', icon:'🗿', series:'Volcanic Origins' },
  { id:4,  name:'Lava Crab',         rarity:'common', icon:'🦀', series:'Volcanic Origins' },
  { id:5,  name:'Cinder Bat',        rarity:'common', icon:'🦇', series:'Volcanic Origins' },
  { id:6,  name:'Magma Slug',        rarity:'common', icon:'🐌', series:'Volcanic Origins' },
  { id:7,  name:'Soot Imp',          rarity:'common', icon:'👺', series:'Volcanic Origins' },
  { id:8,  name:'Flame Moth',        rarity:'common', icon:'🦋', series:'Volcanic Origins' },
  { id:9,  name:'Obsidian Shard',    rarity:'common', icon:'🪨', series:'Volcanic Origins' },
  { id:10, name:'Smoke Wisp',        rarity:'common', icon:'💨', series:'Volcanic Origins' },
  { id:11, name:'Char Beetle',       rarity:'common', icon:'🪲', series:'Volcanic Origins' },
  { id:12, name:'Lava Pebble',       rarity:'common', icon:'🌋', series:'Volcanic Origins' },
  { id:13, name:'Ember Toad',        rarity:'common', icon:'🐸', series:'Volcanic Origins' },
  { id:14, name:'Ash Hound',         rarity:'common', icon:'🐕', series:'Volcanic Origins' },
  { id:15, name:'Cinder Sprite',     rarity:'common', icon:'✨', series:'Volcanic Origins' },
  { id:16, name:'Flame Rat',         rarity:'common', icon:'🐀', series:'Volcanic Origins' },
  { id:17, name:'Scorched Sparrow',  rarity:'common', icon:'🐦', series:'Volcanic Origins' },
  { id:18, name:'Magma Ant',         rarity:'common', icon:'🐜', series:'Volcanic Origins' },
  { id:19, name:'Soot Snail',        rarity:'common', icon:'🐚', series:'Volcanic Origins' },
  { id:20, name:'Ember Frog',        rarity:'common', icon:'🐊', series:'Volcanic Origins' },
  { id:21, name:'Lava Worm',         rarity:'common', icon:'🪱', series:'Volcanic Origins' },
  { id:22, name:'Cinder Crab',       rarity:'common', icon:'🦞', series:'Volcanic Origins' },
  { id:23, name:'Ash Crow',          rarity:'common', icon:'🐧', series:'Volcanic Origins' },
  { id:24, name:'Flame Shrimp',      rarity:'common', icon:'🦐', series:'Volcanic Origins' },
  { id:25, name:'Obsidian Mole',     rarity:'common', icon:'🦔', series:'Volcanic Origins' },
  { id:26, name:'Soot Gecko',        rarity:'common', icon:'🦎', series:'Volcanic Origins' },
  { id:27, name:'Magma Fly',         rarity:'common', icon:'🪰', series:'Volcanic Origins' },
  { id:28, name:'Ember Colt',        rarity:'common', icon:'🐴', series:'Volcanic Origins' },
  { id:29, name:'Char Finch',        rarity:'common', icon:'🐤', series:'Volcanic Origins' },
  { id:30, name:'Lava Snapper',      rarity:'common', icon:'🐢', series:'Volcanic Origins' },
  { id:31, name:'Cinder Ox',         rarity:'common', icon:'🐂', series:'Volcanic Origins' },
  { id:32, name:'Flame Kitten',      rarity:'common', icon:'🐱', series:'Volcanic Origins' },
  { id:33, name:'Ash Bunny',         rarity:'common', icon:'🐇', series:'Volcanic Origins' },
  { id:34, name:'Magma Chick',       rarity:'common', icon:'🐣', series:'Volcanic Origins' },
  { id:35, name:'Soot Lamb',         rarity:'common', icon:'🐑', series:'Volcanic Origins' },
  { id:36, name:'Ember Piglet',      rarity:'common', icon:'🐷', series:'Volcanic Origins' },
  { id:37, name:'Char Duckling',     rarity:'common', icon:'🦆', series:'Volcanic Origins' },
  { id:38, name:'Lava Pup',          rarity:'common', icon:'🐶', series:'Volcanic Origins' },
  { id:39, name:'Cinder Cub',        rarity:'common', icon:'🐻', series:'Volcanic Origins' },
  { id:40, name:'Flame Hamster',     rarity:'common', icon:'🐹', series:'Volcanic Origins' },
  { id:41, name:'Obsidian Turtle',   rarity:'common', icon:'🐠', series:'Volcanic Origins' },
  { id:42, name:'Soot Monkey',       rarity:'common', icon:'🐒', series:'Volcanic Origins' },
  { id:43, name:'Magma Parrot',      rarity:'common', icon:'🦜', series:'Volcanic Origins' },
  { id:44, name:'Ember Hedgehog',    rarity:'common', icon:'🦔', series:'Volcanic Origins' },
  { id:45, name:'Char Caterpillar',  rarity:'common', icon:'🐛', series:'Volcanic Origins' },
  { id:46, name:'Lava Snail',        rarity:'common', icon:'🐌', series:'Volcanic Origins' },
  { id:47, name:'Cinder Bee',        rarity:'common', icon:'🐝', series:'Volcanic Origins' },
  { id:48, name:'Flame Ladybug',     rarity:'common', icon:'🐞', series:'Volcanic Origins' },
  { id:49, name:'Ash Dragonfly',     rarity:'common', icon:'🪲', series:'Volcanic Origins' },
  { id:50, name:'Magma Firefly',     rarity:'common', icon:'🌟', series:'Volcanic Origins' },
  { id:51, name:'Soot Scorpion',     rarity:'common', icon:'🦂', series:'Volcanic Origins' },
  { id:52, name:'Ember Spider',      rarity:'common', icon:'🕷', series:'Volcanic Origins' },
  { id:53, name:'Char Centipede',    rarity:'common', icon:'🐍', series:'Volcanic Origins' },
  { id:54, name:'Lava Mantis',       rarity:'common', icon:'🦗', series:'Volcanic Origins' },
  { id:55, name:'Cinder Moth',       rarity:'common', icon:'🦋', series:'Volcanic Origins' },
  { id:56, name:'Flame Grasshopper', rarity:'common', icon:'🦟', series:'Volcanic Origins' },
  { id:57, name:'Obsidian Ant',      rarity:'common', icon:'🐜', series:'Volcanic Origins' },
  { id:58, name:'Soot Cricket',      rarity:'common', icon:'🎵', series:'Volcanic Origins' },
  { id:59, name:'Magma Weasel',      rarity:'common', icon:'🦦', series:'Volcanic Origins' },
  { id:60, name:'Ember Raccoon',     rarity:'common', icon:'🦝', series:'Volcanic Origins' },

  // ── Common — Frozen Age (60) ──────────────────────────────────────────────
  { id:61,  name:'Ice Shard',        rarity:'common', icon:'❄', series:'Frozen Age' },
  { id:62,  name:'Snow Fox',         rarity:'common', icon:'🦊', series:'Frozen Age' },
  { id:63,  name:'Frost Wisp',       rarity:'common', icon:'🌨', series:'Frozen Age' },
  { id:64,  name:'Blizzard Pup',     rarity:'common', icon:'🐶', series:'Frozen Age' },
  { id:65,  name:'Icicle Sprite',    rarity:'common', icon:'💎', series:'Frozen Age' },
  { id:66,  name:'Snowflake Fairy',  rarity:'common', icon:'🧚', series:'Frozen Age' },
  { id:67,  name:'Frost Bunny',      rarity:'common', icon:'🐇', series:'Frozen Age' },
  { id:68,  name:'Ice Mole',         rarity:'common', icon:'🦔', series:'Frozen Age' },
  { id:69,  name:'Blizzard Bat',     rarity:'common', icon:'🦇', series:'Frozen Age' },
  { id:70,  name:'Snow Owl',         rarity:'common', icon:'🦉', series:'Frozen Age' },
  { id:71,  name:'Frost Beetle',     rarity:'common', icon:'🪲', series:'Frozen Age' },
  { id:72,  name:'Ice Crab',         rarity:'common', icon:'🦀', series:'Frozen Age' },
  { id:73,  name:'Blizzard Toad',    rarity:'common', icon:'🐸', series:'Frozen Age' },
  { id:74,  name:'Snow Sparrow',     rarity:'common', icon:'🐦', series:'Frozen Age' },
  { id:75,  name:'Frost Kitten',     rarity:'common', icon:'🐱', series:'Frozen Age' },
  { id:76,  name:'Ice Lamb',         rarity:'common', icon:'🐑', series:'Frozen Age' },
  { id:77,  name:'Blizzard Chick',   rarity:'common', icon:'🐣', series:'Frozen Age' },
  { id:78,  name:'Snow Piglet',      rarity:'common', icon:'🐷', series:'Frozen Age' },
  { id:79,  name:'Frost Duckling',   rarity:'common', icon:'🦆', series:'Frozen Age' },
  { id:80,  name:'Ice Hamster',      rarity:'common', icon:'🐹', series:'Frozen Age' },
  { id:81,  name:'Blizzard Cub',     rarity:'common', icon:'🐻', series:'Frozen Age' },
  { id:82,  name:'Snow Monkey',      rarity:'common', icon:'🐒', series:'Frozen Age' },
  { id:83,  name:'Frost Parrot',     rarity:'common', icon:'🦜', series:'Frozen Age' },
  { id:84,  name:'Ice Hedgehog',     rarity:'common', icon:'🦔', series:'Frozen Age' },
  { id:85,  name:'Blizzard Bee',     rarity:'common', icon:'🐝', series:'Frozen Age' },
  { id:86,  name:'Snow Ladybug',     rarity:'common', icon:'🐞', series:'Frozen Age' },
  { id:87,  name:'Frost Dragonfly',  rarity:'common', icon:'🪲', series:'Frozen Age' },
  { id:88,  name:'Ice Firefly',      rarity:'common', icon:'✨', series:'Frozen Age' },
  { id:89,  name:'Blizzard Scorpion',rarity:'common', icon:'🦂', series:'Frozen Age' },
  { id:90,  name:'Snow Spider',      rarity:'common', icon:'🕷', series:'Frozen Age' },
  { id:91,  name:'Frost Centipede',  rarity:'common', icon:'🐍', series:'Frozen Age' },
  { id:92,  name:'Ice Mantis',       rarity:'common', icon:'🦗', series:'Frozen Age' },
  { id:93,  name:'Blizzard Moth',    rarity:'common', icon:'🦋', series:'Frozen Age' },
  { id:94,  name:'Snow Grasshopper', rarity:'common', icon:'🦟', series:'Frozen Age' },
  { id:95,  name:'Frost Ant',        rarity:'common', icon:'🐜', series:'Frozen Age' },
  { id:96,  name:'Ice Cricket',      rarity:'common', icon:'🎵', series:'Frozen Age' },
  { id:97,  name:'Blizzard Weasel',  rarity:'common', icon:'🦦', series:'Frozen Age' },
  { id:98,  name:'Snow Raccoon',     rarity:'common', icon:'🦝', series:'Frozen Age' },
  { id:99,  name:'Frost Slug',       rarity:'common', icon:'🐌', series:'Frozen Age' },
  { id:100, name:'Ice Imp',          rarity:'common', icon:'👺', series:'Frozen Age' },
  { id:101, name:'Blizzard Worm',    rarity:'common', icon:'🪱', series:'Frozen Age' },
  { id:102, name:'Snow Shrimp',      rarity:'common', icon:'🦐', series:'Frozen Age' },
  { id:103, name:'Frost Crow',       rarity:'common', icon:'🐧', series:'Frozen Age' },
  { id:104, name:'Ice Fly',          rarity:'common', icon:'🪰', series:'Frozen Age' },
  { id:105, name:'Blizzard Colt',    rarity:'common', icon:'🐴', series:'Frozen Age' },
  { id:106, name:'Snow Finch',       rarity:'common', icon:'🐤', series:'Frozen Age' },
  { id:107, name:'Frost Snapper',    rarity:'common', icon:'🐢', series:'Frozen Age' },
  { id:108, name:'Ice Ox',           rarity:'common', icon:'🐂', series:'Frozen Age' },
  { id:109, name:'Blizzard Rat',     rarity:'common', icon:'🐀', series:'Frozen Age' },
  { id:110, name:'Snow Gecko',       rarity:'common', icon:'🦎', series:'Frozen Age' },
  { id:111, name:'Frost Pebble',      rarity:'common', icon:'💠', series:'Frozen Age' },
  { id:112, name:'Ice Snail',         rarity:'common', icon:'🐚', series:'Frozen Age' },
  { id:113, name:'Blizzard Frog',     rarity:'common', icon:'🐊', series:'Frozen Age' },
  { id:114, name:'Snow Hound',        rarity:'common', icon:'🐕', series:'Frozen Age' },
  { id:115, name:'Frost Turtle',      rarity:'common', icon:'🐠', series:'Frozen Age' },
  { id:116, name:'Ice Caterpillar',   rarity:'common', icon:'🐛', series:'Frozen Age' },
  { id:117, name:'Blizzard Sparrow',  rarity:'common', icon:'🐦', series:'Frozen Age' },
  { id:118, name:'Snow Ant',          rarity:'common', icon:'🐜', series:'Frozen Age' },
  { id:119, name:'Frost Firefly',     rarity:'common', icon:'🌟', series:'Frozen Age' },
  { id:120, name:'Ice Raccoon',       rarity:'common', icon:'🦝', series:'Frozen Age' },

  // ── Rare — Volcanic Origins (25) ─────────────────────────────────────────
  { id:121, name:'Thunder Hawk',      rarity:'rare', icon:'⚡', series:'Volcanic Origins' },
  { id:122, name:'Magma Serpent',     rarity:'rare', icon:'🐍', series:'Volcanic Origins' },
  { id:123, name:'Lava Titan',        rarity:'rare', icon:'🗿', series:'Volcanic Origins' },
  { id:124, name:'Cinder Wolf',       rarity:'rare', icon:'🐺', series:'Volcanic Origins' },
  { id:125, name:'Flame Condor',      rarity:'rare', icon:'🦅', series:'Volcanic Origins' },
  { id:126, name:'Obsidian Golem',    rarity:'rare', icon:'🪨', series:'Volcanic Origins' },
  { id:127, name:'Magma Hydra',       rarity:'rare', icon:'🐲', series:'Volcanic Origins' },
  { id:128, name:'Ember Wyvern',      rarity:'rare', icon:'🦎', series:'Volcanic Origins' },
  { id:129, name:'Soot Chimera',      rarity:'rare', icon:'🦁', series:'Volcanic Origins' },
  { id:130, name:'Lava Basilisk',     rarity:'rare', icon:'🐊', series:'Volcanic Origins' },
  { id:131, name:'Char Manticore',    rarity:'rare', icon:'🦂', series:'Volcanic Origins' },
  { id:132, name:'Flame Gryphon',     rarity:'rare', icon:'🦁', series:'Volcanic Origins' },
  { id:133, name:'Ash Cerberus',      rarity:'rare', icon:'🐕', series:'Volcanic Origins' },
  { id:134, name:'Magma Kraken',      rarity:'rare', icon:'🦑', series:'Volcanic Origins' },
  { id:135, name:'Cinder Sphinx',     rarity:'rare', icon:'🦁', series:'Volcanic Origins' },
  { id:136, name:'Ember Cyclops',     rarity:'rare', icon:'👁', series:'Volcanic Origins' },
  { id:137, name:'Soot Minotaur',     rarity:'rare', icon:'🐂', series:'Volcanic Origins' },
  { id:138, name:'Lava Harpy',        rarity:'rare', icon:'🦅', series:'Volcanic Origins' },
  { id:139, name:'Char Medusa',       rarity:'rare', icon:'🐍', series:'Volcanic Origins' },
  { id:140, name:'Flame Pegasus',     rarity:'rare', icon:'🐴', series:'Volcanic Origins' },
  { id:141, name:'Obsidian Unicorn',  rarity:'rare', icon:'🦄', series:'Volcanic Origins' },
  { id:142, name:'Magma Centaur',     rarity:'rare', icon:'🏹', series:'Volcanic Origins' },
  { id:143, name:'Cinder Naga',       rarity:'rare', icon:'🐍', series:'Volcanic Origins' },
  { id:144, name:'Ember Djinn',       rarity:'rare', icon:'🧞', series:'Volcanic Origins' },
  { id:145, name:'Soot Elemental',    rarity:'rare', icon:'🔥', series:'Volcanic Origins' },

  // ── Rare — Frozen Age (25) ────────────────────────────────────────────────
  { id:146, name:'Blizzard Wolf',     rarity:'rare', icon:'🐺', series:'Frozen Age' },
  { id:147, name:'Moon Fairy',        rarity:'rare', icon:'🧚', series:'Frozen Age' },
  { id:148, name:'Frost Titan',       rarity:'rare', icon:'🗿', series:'Frozen Age' },
  { id:149, name:'Ice Serpent',       rarity:'rare', icon:'🐍', series:'Frozen Age' },
  { id:150, name:'Snow Condor',       rarity:'rare', icon:'🦅', series:'Frozen Age' },
  { id:151, name:'Crystal Golem',     rarity:'rare', icon:'💎', series:'Frozen Age' },
  { id:152, name:'Blizzard Hydra',    rarity:'rare', icon:'🐲', series:'Frozen Age' },
  { id:153, name:'Frost Wyvern',      rarity:'rare', icon:'🦎', series:'Frozen Age' },
  { id:154, name:'Ice Chimera',       rarity:'rare', icon:'🦁', series:'Frozen Age' },
  { id:155, name:'Snow Basilisk',     rarity:'rare', icon:'🐊', series:'Frozen Age' },
  { id:156, name:'Blizzard Manticore',rarity:'rare', icon:'🦂', series:'Frozen Age' },
  { id:157, name:'Frost Gryphon',     rarity:'rare', icon:'🦁', series:'Frozen Age' },
  { id:158, name:'Ice Cerberus',      rarity:'rare', icon:'🐕', series:'Frozen Age' },
  { id:159, name:'Snow Kraken',       rarity:'rare', icon:'🦑', series:'Frozen Age' },
  { id:160, name:'Blizzard Sphinx',   rarity:'rare', icon:'🦁', series:'Frozen Age' },
  { id:161, name:'Frost Cyclops',     rarity:'rare', icon:'👁', series:'Frozen Age' },
  { id:162, name:'Ice Minotaur',      rarity:'rare', icon:'🐂', series:'Frozen Age' },
  { id:163, name:'Snow Harpy',        rarity:'rare', icon:'🦅', series:'Frozen Age' },
  { id:164, name:'Blizzard Medusa',   rarity:'rare', icon:'🐍', series:'Frozen Age' },
  { id:165, name:'Frost Pegasus',     rarity:'rare', icon:'🐴', series:'Frozen Age' },
  { id:166, name:'Ice Unicorn',       rarity:'rare', icon:'🦄', series:'Frozen Age' },
  { id:167, name:'Snow Centaur',      rarity:'rare', icon:'🏹', series:'Frozen Age' },
  { id:168, name:'Blizzard Naga',     rarity:'rare', icon:'🐍', series:'Frozen Age' },
  { id:169, name:'Frost Djinn',       rarity:'rare', icon:'🧞', series:'Frozen Age' },
  { id:170, name:'Ice Elemental',     rarity:'rare', icon:'❄', series:'Frozen Age' },

  // ── Epic — Volcanic Origins (13) ─────────────────────────────────────────
  { id:171, name:'Void Knight',       rarity:'epic', icon:'⚔', series:'Volcanic Origins', story:'A warrior forged in the void between worlds, seeking purpose in endless battle.' },
  { id:172, name:'Inferno Drake',     rarity:'epic', icon:'🐲', series:'Volcanic Origins', story:'Born from the heart of an erupting volcano, its breath melts steel.' },
  { id:173, name:'Magma Colossus',    rarity:'epic', icon:'🗿', series:'Volcanic Origins', story:'A titan of living rock, its footsteps crack the earth and birth new volcanoes.' },
  { id:174, name:'Ember Seraph',      rarity:'epic', icon:'😇', series:'Volcanic Origins', story:'A fallen angel reborn in fire, its wings leave trails of burning light.' },
  { id:175, name:'Lava Leviathan',    rarity:'epic', icon:'🐉', series:'Volcanic Origins', story:'Ancient sea serpent that swims through rivers of molten rock.' },
  { id:176, name:'Cinder Archon',     rarity:'epic', icon:'👁', series:'Volcanic Origins', story:'A cosmic judge who sentences worlds to burn for their transgressions.' },
  { id:177, name:'Flame Behemoth',    rarity:'epic', icon:'🦁', series:'Volcanic Origins', story:'The first beast, older than memory, whose roar ignites the sky.' },
  { id:178, name:'Obsidian Revenant', rarity:'epic', icon:'💀', series:'Volcanic Origins', story:'A warrior who refused death, now bound to obsidian armor for eternity.' },
  { id:179, name:'Soot Lich',         rarity:'epic', icon:'🧙', series:'Volcanic Origins', story:'A sorcerer who traded mortality for mastery over ash and ruin.' },
  { id:180, name:'Magma Warlord',     rarity:'epic', icon:'⚔', series:'Volcanic Origins', story:'Commander of the volcanic legions, undefeated in ten thousand battles.' },
  { id:181, name:'Char Specter',      rarity:'epic', icon:'👻', series:'Volcanic Origins', story:'The ghost of a city consumed by lava, forever searching for its lost home.' },
  { id:182, name:'Ember Valkyrie',    rarity:'epic', icon:'🛡', series:'Volcanic Origins', story:'She rides through eruptions to collect the souls of the worthy fallen.' },
  { id:183, name:'Lava Titan King',   rarity:'epic', icon:'👑', series:'Volcanic Origins', story:"Ruler of the deep earth, his crown is forged from the planet's core." },

  // ── Epic — Frozen Age (12) ────────────────────────────────────────────────
  { id:184, name:'Crystal Dragon',    rarity:'epic', icon:'🐉', series:'Frozen Age', story:'Ancient guardian of the glacial vaults, its scales refract starlight.' },
  { id:185, name:'Aurora Witch',      rarity:'epic', icon:'🧙', series:'Frozen Age', story:'She weaves the northern lights into spells that bend reality.' },
  { id:186, name:'Frost Colossus',    rarity:'epic', icon:'🗿', series:'Frozen Age', story:'A giant of living ice, its breath freezes time itself in a ten-mile radius.' },
  { id:187, name:'Blizzard Seraph',   rarity:'epic', icon:'😇', series:'Frozen Age', story:'An angel of winter who descends to end the warmth of dying worlds.' },
  { id:188, name:'Ice Leviathan',     rarity:'epic', icon:'🐲', series:'Frozen Age', story:'Swims beneath glaciers, its passage causes earthquakes that reshape continents.' },
  { id:189, name:'Snow Archon',       rarity:'epic', icon:'👁', series:'Frozen Age', story:'Keeper of the frozen records, it has witnessed every winter since the first.' },
  { id:190, name:'Blizzard Behemoth', rarity:'epic', icon:'🦁', series:'Frozen Age', story:'The beast of eternal winter, its fur is woven from frozen starlight.' },
  { id:191, name:'Crystal Revenant',  rarity:'epic', icon:'💀', series:'Frozen Age', story:'Preserved in ice for millennia, it awakens to finish a war long forgotten.' },
  { id:192, name:'Frost Lich',        rarity:'epic', icon:'🧙', series:'Frozen Age', story:'A necromancer who froze their own soul to achieve immortality.' },
  { id:193, name:'Ice Warlord',       rarity:'epic', icon:'⚔', series:'Frozen Age', story:'General of the glacial armies, her sword has never known warmth.' },
  { id:194, name:'Snow Specter',      rarity:'epic', icon:'👻', series:'Frozen Age', story:'The spirit of a frozen kingdom, haunting the tundra where its people once lived.' },
  { id:195, name:'Blizzard Valkyrie', rarity:'epic', icon:'🛡', series:'Frozen Age', story:'She descends from the aurora to carry fallen warriors to the eternal ice.' },

  // ── Legendary — Volcanic Origins (4) ─────────────────────────────────────
  { id:196, name:'Celestial Phoenix',  rarity:'legendary', icon:'🦅', series:'Volcanic Origins', story:'Reborn from cosmic fire every millennium, it carries the memory of dead stars.' },
  { id:197, name:'Magma God',          rarity:'legendary', icon:'🌋', series:'Volcanic Origins', story:'The deity of creation itself, who shaped the world by pouring its blood into the void.' },
  { id:198, name:'Infernal Sovereign', rarity:'legendary', icon:'😈', series:'Volcanic Origins', story:'Ruler of the underworld, its throne is the molten heart of the planet.' },
  { id:199, name:'Ember Archangel',    rarity:'legendary', icon:'👼', series:'Volcanic Origins', story:'The first light ever kindled, now guardian of all that burns with purpose.' },

  // ── Legendary — Frozen Age (4) ────────────────────────────────────────────
  { id:200, name:'Eternal Titan',      rarity:'legendary', icon:'👑', series:'Frozen Age', story:'The last king of a frozen empire, preserved in ice for ten thousand years.' },
  { id:201, name:'Frost God',          rarity:'legendary', icon:'❄', series:'Frozen Age', story:'The deity of endings, who will one day freeze the last star and bring silence.' },
  { id:202, name:'Glacial Sovereign',  rarity:'legendary', icon:'🌊', series:'Frozen Age', story:'Ruler of the deep ice, its palace lies at the bottom of a frozen ocean.' },
  { id:203, name:'Blizzard Archangel', rarity:'legendary', icon:'👼', series:'Frozen Age', story:'The last warmth before the eternal winter, a paradox made divine.' },

  // ── Mythic — Beyond (3) ───────────────────────────────────────────────────
  { id:204, name:'The Void Sovereign', rarity:'mythic', icon:'🌌', series:'Beyond', story:'It exists between all things. To hold this card is to touch the edge of existence itself.' },
  { id:205, name:'Primordial Flame',   rarity:'mythic', icon:'☀', series:'Beyond', story:'The first fire that lit the universe. Every flame is its echo.' },
  { id:206, name:'Abyssal Leviathan',  rarity:'mythic', icon:'🌊', series:'Beyond', story:'Older than the oceans it swims in. Its dreams shape the tides.' },
];
